### ISSUE TITLE
Tile icons are not colored

### ISSUE THREAD

**Issue by fabiovin** [bryan2894-playgrnd/SimpleWear#52]
I'm using the app (Watch version 1.15.4, Smartphone version 1.15.3) on Samsung Watch 7 with Wear OS5, and I noticed that sometimes icons on the tile are not colored (see attached screenshot).

To solve the issue I need to remove the tile and add it again.

Could you please check?

![image](https://github.com/user-attachments/assets/55900810-21c3-4a39-8561-9fef6ed351fe)

**Comment by fabiovin** [comment]
Any news about this issue?

It is still present! ;-)

**Comment by thewizrd** [comment]
Issues with tiles should hopefully be resolved in the next update (v1.16.0)

**Comment by thewizrd** [comment]
Should be resolved as of v1.16.0

**Comment by fabiovin** [comment]
I updated the app to version 1.16.1 on both phone and watch but the error persists.
In some cases, some icons are coloured while others are not.

![Image](https://github.com/user-attachments/assets/86c4a9c7-0529-4f77-b6d8-525a1b7d28d5)
